### ISSUE TITLE
small issue on the first " greeting_a_person " method example

### ISSUE THREAD

**Issue by michaelkofron** [learn-co-curriculum/programming-univbasics-3-methods-and-arguments-readme#1]
the first method example where we see greeting_a_person forgets puts before "Hello #{name}"

Just wanted to let you know since the page later tells you to copy and paste this information into the command line! Took me a few minutes to figure out what I was doing wrong cause I was just following the example.

<img width="472" alt="Screen Shot 2019-07-26 at 5 06 02 PM" src="https://user-images.githubusercontent.com/53279060/61983918-04728200-afb7-11e9-84b3-38d1466b47c4.png">

**Comment by maxwellbenton** [comment]
Hi @michaelkofron,

Thank you for opening this issue and providing feedback. I've added in `puts` to this code snippet so that it is consistent with the other code examples in this lesson, which should resolve this issue.

Thank you for contributing to a Learn lesson!
